version: "3.2"

services:
    nginx:
        restart: always
        build: ./nginx
        image: npl/nginx
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - type: bind
              source: ./volumes/conf.d
              target: /etc/nginx/conf.d
            - type: bind
              source: ./volumes/vhost.d
              target: /etc/nginx/vhost.d
            - type: bind
              source: ./volumes/html
              target: /etc/nginx/html
            - type: bind
              source: ./volumes/certs
              target: /etc/nginx/certs
            - type: bind
              source: ./volumes/gencert.sh
              target: /root/gencert.sh
              read_only: true
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }

    generator:
        restart: always
        image: jwilder/docker-gen
        container_name: ${COMPOSE_PROJECT_NAME}_generator
        volumes:
            - type: bind
              source: ./volumes/conf.d
              target: /etc/nginx/conf.d
            - type: bind
              source: /var/run/docker.sock
              target: /tmp/docker.sock
              read_only: true
            - type: bind
              source: ./volumes/proxy/nginx.tmpl
              target: /etc/docker-gen/templates/nginx.tmpl
              read_only: true
        entrypoint: /usr/local/bin/docker-gen -notify-sighup ${COMPOSE_PROJECT_NAME}_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }
