version: "3.7"

services:
    nginx:
        container_name: proxy_nginx
        image: proxy/nginx
        build: ./nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - confd:/etc/nginx/conf.d:rw
            - vhostd:/etc/nginx/vhost.d:rw
            - certs:/etc/nginx/certs:rw
        logging:
            driver: "json-file"
            options: { max-size: "50k", max-file: "3" }

    generator:
        container_name: proxy_generator
        image: nginxproxy/docker-gen
        restart: always
        command: -notify-sighup proxy_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - confd:/etc/nginx/conf.d:rw
            - vhostd:/etc/nginx/vhost.d:rw
            - certs:/etc/nginx/certs:rw
            - ./etc/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        logging:
            driver: "json-file"
            options: { max-size: "50k", max-file: "3" }

volumes:
    certs:
    confd:
    vhostd:
