version: "2"

services:
    nginx:
        restart: always
        build: ./nginx
        image: npl/nginx
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/etc/nginx/conf.d"
            - "/etc/nginx/vhost.d"
            - "/usr/share/nginx/html"
            - "./volumes/gencert.sh:/root/gencert.sh:ro"
            - "./volumes/certs:/etc/nginx/certs:rw"

    nginx-gen:
        restart: always
        image: jwilder/docker-gen
        container_name: ${COMPOSE_PROJECT_NAME}_nginx_gen
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./volumes/proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
        volumes_from:
            - nginx
        entrypoint: /usr/local/bin/docker-gen -notify-sighup ${COMPOSE_PROJECT_NAME}_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
