version: "2.2"

services:
    nginx:
        restart: always
        build: ./nginx
        image: npl/nginx
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        depends_on:
            - generator
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./volumes/conf.d:/etc/nginx/conf.d:rw
            - ./volumes/vhost.d:/etc/nginx/vhost.d:rw
            - ./volumes/html:/etc/nginx/html:rw
            - ./volumes/certs:/etc/nginx/certs:rw
            - ./volumes/gencert.sh:/root/gencert.sh:ro
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }
        cpus: 0.1
        mem_limit: 64M

    generator:
        restart: always
        image: jwilder/docker-gen
        container_name: ${COMPOSE_PROJECT_NAME}_generator
        volumes:
            - ./volumes/conf.d:/etc/nginx/conf.d:rw
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./volumes/proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
        entrypoint: /usr/local/bin/docker-gen -notify-sighup ${COMPOSE_PROJECT_NAME}_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }
        cpus: 0.1
        mem_limit: 64M
